export const monthsData = [
    {
        id: 1,
        month: "декабрь",
        monthNumber: 1,
        days: [
            { id: 1, status: "none" },
            { id: 2, status: "none" },
            { id: 3, dayNumber: 1 },
            { id: 4, dayNumber: 2, status: "late" },
            { id: 5, dayNumber: 3, status: "absentValid" },
            { id: 6, dayNumber: 4, status: "weekend" },
            { id: 7, dayNumber: 5, status: "weekend" },
            { id: 8, dayNumber: 6 },
            { id: 9, dayNumber: 7 },

            { id: 10, dayNumber: 8 },
            { id: 11, dayNumber: 9, status: "late" },
            { id: 12, dayNumber: 10, status: "late" },
            { id: 13, dayNumber: 11, status: "weekend" },
            { id: 14, dayNumber: 12, status: "weekend" },
            { id: 15, dayNumber: 13, status: "absent" },
            { id: 16, dayNumber: 14, status: "absent" },

            { id: 17, dayNumber: 15 },
            { id: 18, dayNumber: 16 },
            { id: 19, dayNumber: 17, status: "absentValid" },
            { id: 20, dayNumber: 18, status: "weekend" },
            { id: 21, dayNumber: 19, status: "weekend" },
            { id: 22, dayNumber: 20, status: "late" },
            { id: 23, dayNumber: 21, status: "late" },

            { id: 24, dayNumber: 22 },
            { id: 25, dayNumber: 23, status: "late" },
            { id: 26, dayNumber: 24, status: "late" },
            { id: 27, dayNumber: 25, status: "weekend" },
            { id: 28, dayNumber: 26, status: "weekend" },
            { id: 29, dayNumber: 27 },
            { id: 30, dayNumber: 28, status: "absentValid" },

            { id: 31, dayNumber: 29, status: "absentValid" },
            { id: 32, dayNumber: 30, status: "absentValid" },
        ],
    },
    {
        id: 2,
        month: "январь",
        monthNumber: 2,
        days: [
            { id: 1, status: "none" },
            { id: 2, status: "none" },
            { id: 3, status: "none" },

            { id: 4, dayNumber: 1 },
            { id: 5, dayNumber: 2 },
            { id: 6, dayNumber: 3, status: "weekend" },
            { id: 7, dayNumber: 4, status: "weekend" },
            { id: 8, dayNumber: 5, status: "late" },
            { id: 9, dayNumber: 6 },
            { id: 10, dayNumber: 7 },

            { id: 11, dayNumber: 8 },
            { id: 12, dayNumber: 9 },
            { id: 13, dayNumber: 10, status: "weekend" },
            { id: 14, dayNumber: 11, status: "weekend" },
            { id: 15, dayNumber: 12, status: "absentValid" },
            { id: 16, dayNumber: 13 },
            { id: 17, dayNumber: 14, status: "late" },

            { id: 18, dayNumber: 15 },
            { id: 19, dayNumber: 16 },
            { id: 20, dayNumber: 17, status: "weekend" },
            { id: 21, dayNumber: 18, status: "weekend" },
            { id: 22, dayNumber: 19 },
            { id: 23, dayNumber: 20, status: "absent" },
            { id: 24, dayNumber: 21 },

            { id: 25, dayNumber: 22 },
            { id: 26, dayNumber: 23 },
            { id: 27, dayNumber: 24, status: "weekend" },
            { id: 28, dayNumber: 25, status: "weekend" },
            { id: 29, dayNumber: 26, status: "late" },
            { id: 30, dayNumber: 27 },
            { id: 31, dayNumber: 28 },

            { id: 32, dayNumber: 29 },
            { id: 33, dayNumber: 30 },
            { id: 34, dayNumber: 31, status: "weekend" },
        ],
    },
    {
        id: 3,
        month: "февраль",
        monthNumber: 3,
        days: [
            { id: 1, status: "none" },

            { id: 2, dayNumber: 1 },
            { id: 3, dayNumber: 2 },
            { id: 4, dayNumber: 3 },
            { id: 5, dayNumber: 4 },
            { id: 6, dayNumber: 5, status: "weekend" },
            { id: 7, dayNumber: 6, status: "weekend" },
            { id: 8, dayNumber: 7 },

            { id: 9, dayNumber: 8 },
            { id: 10, dayNumber: 9 },
            { id: 11, dayNumber: 10 },
            { id: 12, dayNumber: 11 },
            { id: 13, dayNumber: 12, status: "weekend" },
            { id: 14, dayNumber: 13, status: "weekend" },
            { id: 15, dayNumber: 14 },

            { id: 16, dayNumber: 15 },
            { id: 17, dayNumber: 16 },
            { id: 18, dayNumber: 17 },
            { id: 19, dayNumber: 18, status: "weekend" },
            { id: 20, dayNumber: 19, status: "weekend" },
            { id: 21, dayNumber: 20, status: "weekend" },
            { id: 22, dayNumber: 21, status: "weekend" },

            { id: 23, dayNumber: 22, status: "weekend" },
            { id: 24, dayNumber: 23, status: "weekend" },
            { id: 25, dayNumber: 24, status: "weekend" },
            { id: 26, dayNumber: 25, status: "weekend" },
            { id: 27, dayNumber: 26, status: "weekend" },
            { id: 28, dayNumber: 27, status: "weekend" },
            { id: 29, dayNumber: 28, status: "weekend" },
        ],
    },
];
