import type { Quarter } from "./types";

const SUBJECT_NAMES = [
    "Белорусский язык",
    "Белорусская литература",
    "Русский язык",
    "Русская литература",
    "Английский язык",
    "Математика",
    "Информатика",
    "Всемирная история",
    "История Беларуси",
    "Обществоведение",
    "География",
    "Биология",
    "Физика",
    "Трудовое обучение",
    "Физкультура",
    "Химия",
];

function createSubjects(grades: (string | number)[]) {
    return SUBJECT_NAMES.map((name, index) => ({
        name: name,
        grade: grades[index] || "-",
    }));
}

export const quartersData: Quarter[] = [
    {
        id: "q1-2025",
        title: "1 четверть 2025-2026",
        period: "1 сентября - 1 ноября 2025",
        subjects: createSubjects([9, 9, 9, 8, 10, 9, 9, 9, 10, 10, 9, 8, 10, 10, 9, 8]),
        averageGrade: 9.13,
        isApproximately: false,
    },
    {
        id: "q2-2025",
        title: "2 четверть 2025-2026",
        period: "9 ноября - 25 декабря 2025",
        subjects: createSubjects([10, 10, 9, 10, 10, 9, 10, 9, 10, 10, 10, 9, 9, 10, 9, 9]),
        averageGrade: 9.56,
        isApproximately: false,
    },
    {
        id: "q3-2026",
        title: "3 четверть 2025-2026",
        period: "9 ноября - 25 декабря 2025",
        subjects: createSubjects([
            "~9",
            "9",
            "~8",
            "9",
            "~10",
            "9",
            "~9",
            "~10",
            "~10",
            "-",
            "~10",
            "~9",
            "~10",
            "~9",
            "~8",
            "-",
        ]),
        averageGrade: 0,
        isApproximately: false,
    },
    {
        id: "q4-2026",
        title: "4 четверть 2025-2026",
        period: "29 марта - 11 июня 2026",
        subjects: createSubjects([
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
            "-",
        ]),
        averageGrade: 0,
        isApproximately: false,
    },
    {
        id: "year-2026",
        title: "Годовая оценка",
        subjects: createSubjects([
            "~9",
            "9",
            "~8",
            "9",
            "~10",
            "~9",
            "~9",
            "~10",
            "~10",
            "~9",
            "~10",
            "~9",
            "~9",
            "~10",
            "-",
            "~",
        ]),
        averageGrade: "~9.3",
        isApproximately: true,
    },
];
