# Generated by Django 6.0.7 on 2026-07-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='director',
        ),
    ]
