# Generated by Django 6.0.7 on 2026-08-03 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_school', '0002_remove_school_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='schedule_lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='smart_school.schedulelesson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quartergrade',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='smart_school.quarter'),
        ),
    ]
