# Generated by Django 6.0.7 on 2026-08-05 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_school', '0003_grade_schedule_lesson_alter_quartergrade_quarter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='date',
        ),
        migrations.AddField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 5, 8, 20, 6, 187693, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
