# Generated by Django 6.0.7 on 2026-08-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_school', '0004_remove_grade_date_grade_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='school_classes',
            field=models.ManyToManyField(related_name='subjects', to='smart_school.schoolclass'),
        ),
    ]
