# Generated by Django 6.0.7 on 2026-08-08 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_school', '0005_subject_school_classes'),
        ('users', '0006_remove_useractivation_activation_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_absent', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='smart_school.schedulelesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='users.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lesson', 'student', 'date'), name='unique_student_lesson_attendance')],
            },
        ),
    ]
