# Generated by Django 6.0.7 on 2026-08-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_school', '0005_subject_school_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='schedule_lesson',
        ),
    ]
