# Generated by Django 6.0.7 on 2026-08-26 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_school', '0006_remove_grade_schedule_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='created_at',
        ),
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
