# Generated by Django 6.0.7 on 2026-10-04 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_school', '0007_remove_grade_created_at_grade_date'),
        ('users', '0013_remove_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='schedule_lesson',
        ),
        migrations.CreateModel(
            name='SchoolAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dayNumber', models.PositiveSmallIntegerField()),
                ('is_absent', models.BooleanField(default=False)),
                ('is_valid_reason', models.BooleanField(default=False)),
                ('is_late', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_attendance', to='users.student')),
            ],
        ),
    ]
