# Generated by Django 6.0.7 on 2026-07-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivation',
            name='activation_token',
        ),
    ]
