# Generated by Django 6.0.7 on 2026-08-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_useractivation_activation_token'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
