# Generated by Django 6.0.7 on 2026-08-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pending_phone',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
